### ISSUE TITLE
Demos are not working due to CORS

### ISSUE THREAD

**Issue by avorio** [DDMAL/IIIF-AV-player#41]
Hi @ahankinson! Long time no see.

I recently noticed that the [two IIIF-AV-player demos](https://ddmal.music.mcgill.ca/IIIF-AV-player/) are not working due to CORS restrictions.

> Access to fetch at 'https://ddmal.github.io/IIIF-AV-player/samples/Chopin_Etude_Op_10_No_9_aud/manifest_chopin_etude_aud.json' from origin 'https://ddmal.music.mcgill.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I believe you can fix this by changing the domain from `ddmal.github.io` to `ddmal.music.mcgill.ca` in both the manifest and MEI URLs.

Thanks!

**Comment by vigliensoni** [comment]
Hi @avorio,

Thanks for pointing this out. The links were fixed to avoid the redirect and prevent the CORS issue.

Thank you!
